---
title: "Evaluation du blog scientifique"
subtitle: "La forme" 
author: "Guyliann Engels & Philippe Grosjean"
date: "`r Sys.Date()`"
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#", fig.align = "center")
```


Dans les cadres du cours de [English for Science](http://applications.umons.ac.be/web/en/pde/2019-2020/ue/US-B2-SCBIOL-001-M.htm) les étudiants sont amenés à rédiger un blog. Le contenu lié à ce blog doit respecter les consignes disponibles sur [moodle](https://moodle.umons.ac.be) (`English for Science -> general organisation -> Course description, evaluation and instructions 19-20`). Le site web doit respecter le template fournit dans le cadre du cours de Science des données biologiques. La forme de ce blog doit respecter les consignes également disponible sur [moodle](https://moodle.umons.ac.be) (`Science des données I : visualisation -> blog`)

Vous serez donc évalué par vos professeurs d'anglais pour **le fond** et par vos professeurs de sciences des données biologiques pour **la forme**.

Les critères d'évaluation sont les suivants :

- création du dépot
- mise en ligne du blog
- respect du nom du dépot 
- réalisation de commit et push
- édition de la section about
- ajout d'article sur le blog
- ajout d'images
- ajout d'une section commentaire avec disqus



